### ISSUE TITLE
Possible to avoid modifying model file after initial generation in simple cases?

### ISSUE THREAD

**Issue by HoldYourWaffle** [Bounced-Inc/mongoose-tsgen#11]
Great title-gore material this one. I guess that's what I get for exploring new modules at midnight...

The README tells me that I have to modify my model file to add some imports after the initial generator run.
Based on the example in the README, this is necessary for "2" things:
- Virtuals, methods, statics and queries that need these types
- The generics have to be added to this line at the bottom of the file:
```ts
export const User: UserModel = mongoose.model<UserDocument, UserModel>("User", UserSchema);
```

It seems to me that this last line (and the following export) can just as easily be generated and put in an output file, saving the chicken-and-egg dance for the simple cases.

_Disclaimer: I only just discovered this module and am quite new to mongoose, so there's a good chance that this is a very silly suggestion..._

**Comment by francescov1** [comment]
Could definitely be generated, but IMO I think it's a bit overkill since its really quick to make the change yourself and gives you better context on what's going on in the background. Also could present additional edge cases based on how user's initialize their own schemas.
