### ISSUE TITLE
Generic type 'Model<T>' requires 1 type argument

### ISSUE THREAD

**Issue by www-chique** [Bounced-Inc/mongoose-tsgen#23]
Right off the bat, I'm new at the whole Typescript and Mongoose, so maybe I am doing something wrong.

I am facing this issue.
While using "npx mtgen", it generates UserModel like so
```
export interface UserModel
  extends mongoose.Model<UserDocument, UserQueries>,
    UserStatics {}

```
However, the line `mongoose.Model<UserDocument, UserQueries>` shows an error from ts, which is
**_Generic type 'Model<T>' requires 1 type argument_**

So when I manually remove "UserQueries", and just use `mongoose.Model<UserDocument>` instead, everything works just fine.
Not sure if it's due to using a more updated version of mongoose, or something.

Any help is appreciated.
For now I am manually removing the ***Queries like I mentioned, to make this work.

A side-note:
I am a big fan of this tool, and it absolutely makes my work 100 times easier. Much better than the other (sometimes more popular) options out there, which requries you to learn a completely new API just to write the schema, and moreover sometimes it doesn't work. **mongoose-tsgen** is underrated, and I love the "compiler" approach, it works seamlessly with existing Schema structure.

**Comment by www-chique** [comment]
Never mind, someone already reported.
https://github.com/Bounced-Inc/mongoose-tsgen/issues/19

**Comment by francescov1** [comment]
Praise is much appreciated 😊 I had the same experience with the other modules which led me to write this!
