### ISSUE TITLE
Schema with more than 13 ObjectId property throws "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by henaff** [Bounced-Inc/mongoose-tsgen#35]
Hi, with a lot of schema with mongoose ^5.11.16, if i use more than 13 ObjectId in Types "RangeError: Maximum call stack size exceeded" is throwed. No matter the order or the file where they are placed.

![image](https://user-images.githubusercontent.com/54863020/108480021-ba3aab00-7296-11eb-9b0b-ddcc7680e88f.png)

**Comment by francescov1** [comment]
Hi @henaff,

Have you tried using the newest version? Many of these niche issues have been fixed. The preferable solution would be to update to the latest version, but note that this requires Mongoose v5.11+. If you need to use a version of Mongoose lower than 5.11, you can update to mongoose-tsgen v6.0.10 with `npm install mongoose-tsgen@6.0.10`.

Let me know if the issue is still present after updating!

**Comment by kurtcarpenter** [comment]
Also getting "Maximum call stack size exceeded" with a slightly different example involving String defaults. Not sure if this has the same root cause as the original issue. `mongoose@5.11.15` `mongoose-tsgen@7.0.11`

```typescript
import mongoose from 'mongoose';

export default mongoose.model('foo', new mongoose.Schema({
  test: {
    type: {
      str: String
    },
    default: {
      str: 'something' // adding this property default causes the error
    }
  }
}));
```

**Comment by francescov1** [comment]
@kurtcarpenter I have not seen that syntax for Mongoose schemas before. If you define your types at the source it should fix the issue:

```typescript
import mongoose from 'mongoose';

export default mongoose.model('foo', new mongoose.Schema({
  test: {
     str: {
        type: String,
        default: 'something'
     }
  }
}));
```

Does your syntax work as expected with Mongoose? If so I will look to add support for it as well!

**Comment by francescov1** [comment]
Closing this for housekeeping, feel free to re-open if this is still an issue!
