### ISSUE TITLE
Keep the name same as file name or configurable in some way?

### ISSUE THREAD

**Issue by shahidcodes** [Bounced-Inc/mongoose-tsgen#41]
The interfaces that are generated are in camel-case but model file names start with `Uppercase`. Is it possible to keep the same case? Or better to have it configurable maybe through a custom field in the exported model?

![image](https://user-images.githubusercontent.com/17620737/109372800-82081d80-78d1-11eb-829d-619405b7949d.png)

**Comment by francescov1** [comment]
Hey @shahidcodes! This currently isn't possible but as a workaround you can specify additional type aliases through the `imports` option in the config. Something like this:

```
# "users" is the type name you want to reference in your code, "User" is the generated name

npx mtgen --imports "export type users = User"
```

Let me know if that works!

**Comment by shahidcodes** [comment]
The works around I am using is setting collection name as first caps when registering model (i.e. `mongoose.model('User', user)`
